using BepInEx;
using BepInEx.Logging;
using TimberbornAPI;

namespace ModName
{
    [BepInPlugin("name.plugin.modname", "ModName", "1.0.0")]
    [BepInDependency("com.timberapi.timberapi")]
    public class ModNamePlugin : BaseUnityPlugin
    {
        internal static ManualLogSource Log;

        private void Awake()
        {
            // Add static logger for internal mod use
            Log = Logger;

            // Plugin startup logic
            Logger.LogInfo($"Plugin ModName is loaded!!");

            // Autogenerated first Configurator
            TimberAPI.DependencyRegistry.AddConfigurator(new ModNameConfigurator());
        }
    }
}